### ISSUE TITLE
Separate data files and data format validation?

### ISSUE THREAD

**Issue by dnch** [hexorx/countries#112]
Just a couple of queries:

1. Is there a reason the database is packaged as a single file? It seems that maintenance would be easier if they were split into separate files.

2. Is there a specification / validator for the schema? A rake task that ensures compliance would be handy.

Happy to take these on if you're interested.

**Comment by rposborne** [comment]
Not yet! But I think as the list grows it's clear it needs to be broken out.  A validator and an importer from various other sources are on the horizon.
