### ISSUE TITLE
Feature request - Have aliases for countries

### ISSUE THREAD

**Issue by barnaclebarnes** [hexorx/countries#131]
It would be great if you could have aliases for countries (not just translations). For example "United States of America" Is also known as:

* USA
* U.S.A
* America

This would make matching country names from databases a lot easier.

**Comment by rposborne** [comment]
Isn't this done via the "names" field?

**Comment by barnaclebarnes** [comment]
In the latest version putting this in an initialiser works:

```ISO3166::Country.new('CY').names << 'Northern Cyprus'```

So closing as there is a way to do what I wanted originally.

**Comment by rposborne** [comment]
@barnaclebarnes thanks for the clean up!
