### ISSUE TITLE
[Feature / Discussion] Sync country names <--> Debian

### ISSUE THREAD

**Issue by steakknife** [hexorx/countries#133]
Debian maintains an enormous list of N countries x M languages, and it's currently available statically and live through the [i18n_data gem](https://github.com/grosser/i18n_data).

Pushing existing hard work upstream to http://translationproject.org/domain/index.html would also make them available to Mint, Ubuntu, Debian and other distros too.

Either or both of these could make the countries gem even more awesome and show F(L)OSS collaboration / leadership.

**Comment by rposborne** [comment]
Agreed, this is data we are currently picking through and adding.  Maybe simple depend on this gem to pull in the translations for country name? @hexorx thoughts?

**Comment by hexorx** [comment]
I think making i18n_data dependency makes the most sense. No reason to try and duplicate the data in countries gem. It would be nice to make it optional, countries gem maybe keeps the names in the top 3 languages then defers to i18n_data if it is available.

**Comment by rposborne** [comment]
I am trying to image what the data structure would end up looking like.   As I think the i18n_data has it right country code + language, vs just names that become unstructured slang. I like aliases, but should they be kept as language specific?   Maybe we just fully defer that aspect of the gem to i18n and then split up the data files to be country specific, dropping the translations.

**Comment by rposborne** [comment]
So I whipped together #211 which basically just hands off translations, all_translated and names to i18n_data gem.   I also have it breaking out the files themselves, as these merge conflicts are getting tough to handle.

**Comment by rposborne** [comment]
Closing as #211 has been merged.
