### ISSUE TITLE
Should 'UK' be recognized?

### ISSUE THREAD

**Issue by mmustala** [hexorx/countries#139]
I just found out that UK is not an official short name for United Kingdom and Countries gem doesn't find it when trying 'Country.new('UK')'. This really surprises me as 'UK' is so widely used. Should Countries gem have support for this kind of widely used but unofficial short names? Is there many more of these?

Maybe 'UK' could be added as an alternative name for United Kingdom.

**Comment by kylewelsby** [comment]
`UK` is a exceptional reservation for the United Kingdom.

`UK` could be an alias of `GB` as `GB` is the official `ISO 3166-2` code for the United Kingdom.

* England and Wales (consisting of England and Wales)
* Great Britain (consisting of England, Scotland, and Wales)
* United Kingdom (consisting of England, Northern Ireland, Scotland, and Wales)

**Comment by rposborne** [comment]
I think if we deviate too much from the standard we risk having do ISO's job.   Going to close in favor of adhering to standards.
