### ISSUE TITLE
Example for ExchangeBank does not work

### ISSUE THREAD

**Issue by mrmanishs** [hexorx/countries#14]
I installed latest countries, money, and currencies gems, and the exchangebank example does not work:

>> Money.default_bank = Currency::ExchangeBank.new
=> #<ISO4217::Currency::ExchangeBank:0x1106187b0 @mutex=#<Mutex:0x110618378>, @rates={}>
>> Money.us_dollar(100).exchange_to("CAD")
NoMethodError: undefined method `exchange_with' for #<ISO4217::Currency::ExchangeBank:0x1106187b0>
        from /Library/Ruby/Gems/1.8/gems/money-4.0.2/lib/money/money.rb:320:in `exchange_to'
        from (irb):60

**Comment by kofronpi** [comment]
I have the same problem with latests version of all gems.

**Comment by dgilperez** [comment]
Why is this issue closed? This isn't working with last version ...

**Comment by rposborne** [comment]
@dgilperez I think it was determined to be a upstream issue,  but we have switched maintainers.   I'll reopen and see if I can dig in.

**Comment by rposborne** [comment]
@dgilperez going to close this as it's reasonable outside the scope of this gem.  The smell is the example code doesn't even talk to this gem!  Only our dependencies, which I am debating dropping in favor of leaning directly on the highly maintained Money gem. Which includes the same data https://github.com/RubyMoney/money/blob/master/config/currency_iso.json

**Comment by dgilperez** [comment]
@rposborne fair enough, but in any case I'd change the misleading information in the README.

**Comment by rposborne** [comment]
@dgilperez 100% agree,  already done on our 2.0 branch will bring it back to the 1.x series shortly.
