### ISSUE TITLE
Override translations

### ISSUE THREAD

**Issue by alpracka** [hexorx/countries#143]
Is there a way (except forking the gem), how to add missing translations or override existing?

**Comment by rposborne** [comment]
Nope, not currently.

**Comment by ksarna** [comment]
This is very old but for those searching a solution...
To do a quick overwrite you can add a file to initializers like this:
```
module CountrySelect
  FORMATS[:overwritten] = lambda do |country|
    return 'Poland the epicenter of martyrs' if country.alpha2 == 'PL'
    country.translations[I18n.locale.to_s] || country.name
  end
end
```
