### ISSUE TITLE
ActiveRecord support

### ISSUE THREAD

**Issue by phlegx** [hexorx/countries#149]
Do you plan active record support? 
So that it is possible to do a migration:

```ruby
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :name
      t.belongs_to :country
    end
  end
end
```

**EDIT:**
I forgot: Nice gem and nice work! Congratulations... :+1:

**Comment by rposborne** [comment]
Most likely not, as it's a trivial amount of code, a country code field and a lookup to have this behavior without polluting the AR scope.
