### ISSUE TITLE
Release an up-to-date version of this great gem

### ISSUE THREAD

**Issue by simonweil** [hexorx/countries#154]
And thank you for a great gem :)

**Comment by rposborne** [comment]
It looks there is quite a lot of outstanding PR's that include raw data that are outstanding.  @hexorx do you need help maintaining this gem?

**Comment by hexorx** [comment]
@rposborne some help would be welcome.

**Comment by rposborne** [comment]
What can I do for you? I am happy to take on anything you want to offload.

**Comment by opensourceame** [comment]
Agreed the state of things doesn't look good. The fact that there are nearly half as many forks as stars on this repo is a good indicator of how it's falling short of peoples' needs.

hexorx, if you can't maintain the gem maybe let someone else take it over?

In the meantime can anyone recommend a few of the better forks?

**Comment by rposborne** [comment]
@hexorx Would you like me to vet issues and pull requests just to par down the workload?   We have a good number of dups on various things.

**Comment by hexorx** [comment]
@rposborne that would be a great help. If you can help me determine the top issues I'll start getting things knocked out.

**Comment by rposborne** [comment]
@hexorx could I have access to issue administration on the repo, so I can close and label issues?

**Comment by hexorx** [comment]
@rposborne done, and thank you. If you want to setup some milestones so we can figure out what to put in a minor version bump, and what we should put in 1.0.

**Comment by rposborne** [comment]
@hexorx I would like to fast track data fixes / completing the data set, I will save code features for milestones.

**Comment by rposborne** [comment]
@hexorx It looks like I can't add labels :cry: I think i will go ahead and merge data set updates that I can verify or have good sources in the PR.

**Comment by hexorx** [comment]
@rposborne you should have full access, merge away.

**Comment by rposborne** [comment]
@hexorx lets cut a gem, say 0.10.0. Very little ruby has changed but with the number of merges i think we need at least a minor version bump.  I cleaned up most of the issues, and we have a good number of outstanding translations that need to be brought up to speed.  I think we should consider simplifying the data structure for maintainability as a few people aren't that aware of the white spaces issues that make merging requests in viable.

**Comment by hexorx** [comment]
@rposborne thank you for all your help on this! Have a pizza on me (via @changetip). I'll push 0.10.0 tonight.

**Comment by changetip** [comment]
Hi @rposborne, @hexorx sent you a Bitcoin tip worth a pizza (42,976 bits/$10.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/381164)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by rposborne** [comment]
@hexorx just made my night!

**Comment by rposborne** [comment]
Closing as we now have (0.10.0)[https://rubygems.org/gems/countries/versions/0.10.0]
