### ISSUE TITLE
How to associate to a country in a ActiveRecord model?

### ISSUE THREAD

**Issue by simonweil** [hexorx/countries#155]
When I assign a `Country` to a `User` in rails, how should I save it?
Can I use ActiveRecord associations?

**Comment by yurijmi** [comment]
@alfonsomunozpomer +

Also you need to add this code (don't forget to change attribute name) to your model to use gem's methods
```
def country
  Country.new read_attribute(:country)
end
```

**Comment by rposborne** [comment]
I generally save the country code, and do a lookup like @yurijmi suggests.
