### ISSUE TITLE
Russian Federation displaying as Russia in country_select

### ISSUE THREAD

**Issue by mikestone14** [hexorx/countries#172]
I am using your Gem with the `country_select` gem to allow registering users to select their country. In certain circumstances "Russian Federation" is being shown as "Russia". Since I am also using your country names for form validation an error is being thrown as it expects "Russian Federation". 

This could be due to the English translation of "Russian Federation" to "Russia" in `countries.yml`.

**Comment by rposborne** [comment]
Accepted #128
