### ISSUE TITLE
Not so awesome print with awesome_print

### ISSUE THREAD

**Issue by fgarcia** [hexorx/countries#183]
There is an funny error for users testing this gem in theirs shells:

    2.1.3 (main):0 > require 'countries'; Country['US']
    (pry) output error: #<NoMethodError: undefined method `data' for #<Object:0x007f85fb0e1518>>

I tracked down the error to my Ruby shell (pry) loading the [awesome_print](https://github.com/michaeldv/awesome_print) gem, and have tested that this also fails for **irb**

The way to reproduce the error is just loading the shell without awesome print. The Country class prints OK. Now if you do...

    require "awesome_print"
    AwesomePrint.pry!
    # ... or ... AwesomePrint.irb!

The error appears

**Comment by rposborne** [comment]
Should be solved by #177
