### ISSUE TITLE
Slightly breaks country-select gem

### ISSUE THREAD

**Issue by yas4891** [hexorx/countries#200]
Hi,

adding this gem to my rails app slightly broke `country-select`

Previous code to add priority countries: 
`= country_select :user, :country, ['Germany', 'Netherlands', 'United States', 'United Kingdom']`

With `countries` installed this code is necessary: 
`= country_select :user, :country, [['Germany', 'DE'], ['Netherlands', 'NL'], ['United States', 'US'], ['United Kingdom', 'GB']]`

**Comment by rposborne** [comment]
What version of country-select are you using?

**Comment by yas4891** [comment]
1.1.1

**Comment by rposborne** [comment]
I recommend using 
```
gem install country_select
```
Note the underscore vs hypen [country-select](https://rubygems.org/gems/country-select) is very old and deprecated.
