### ISSUE TITLE
New Cuban subdivisions, and renaming old ones

### ISSUE THREAD

**Issue by cllns** [hexorx/countries#208]
In 2011, Cuba changed its provinces. ISO 3166-2 only recently updated to reflect this (on 2014-10-29): https://www.iso.org/obp/ui/#iso:code:3166:CU

#### Problem
Before 2011 (and, for ISO 3166-2, before Oct. 2014):

`CU-02` was **La Habana** and contained the area outside of the city of Havana.
`CU-03` was a province for just the city of Havana, named **Ciudad de La Habana**

After 2011 (and, for ISO 3166-2, after Oct. 2014):

`CU-02` was split into 
- **Artemisa** `CU-15` and
- **Mayabeque** `CU-16`.

That means `CU-02` was removed. 

**Also:**
`CU-03` took this opportunity to rename itself from **Ciudad de La Habana** to just **La Habana** (the old name of `CU-02`), since it no longer needed to specify the city vs the province of Havana.

Also worth noting (to make things more complicated) Artemisa also took 3 municipalities from its neighbor (`CU-01`) when it was created.

#### Proposed Solution
I feel like it might be a bad idea to just remove CU-02 altogether, since that will cause problems.

So, in order to adhere to ISO 3166-2 (which we want to do, I think) we need these:
`CU-03`: La Habana
`CU-15`: Artemisa
`CU-16`: Mayabeque

However, I think removed subdivisions are undefined behavior, so for that, here are the options I see:

1. Remove CU-02
2. Keep CU-02 and name it 'Provincia de la Habana'
3. a. Keep CU-02 and name it 'Provincia de la Habana (deprecated)'
3. b. Keep CU-02 and name it 'Provincia de la Habana (obsoleta)'

My preference is for 2. 
(Then 3b, then 3a, then 1)

**Comment by rposborne** [comment]
Could we get a PR for suggestion number 2?

**Comment by cllns** [comment]
@rposborne #212 !

**Comment by cllns** [comment]
@rposborne Also:

1. Should we change `CU-02` to "Antigua provincia de La Habana"? That's the name here: https://es.wikipedia.org/wiki/Antigua_provincia_de_La_Habana
"Antigua provincia" means "Former province" (according to Google Translate), which helps signify that it shouldn't be used.

2. I'm willing to add their old names to the `names` field, if you think that makes sense.

**Comment by rposborne** [comment]
I like "Antigua provincia de La Habana" over saying deprecated or something similar. Espically if it conveys the correct meaning. 

Is there something similar for ```CU-03```?

**Comment by cllns** [comment]
@rposborne I like that too.

It's not really relevant for `CU-03`, as it existed before (with the same boundaries). It just changed names.

 We *could* keep `CU-03`'s former name of **Ciudad de La Habana** but that breaks with the official name from ISO 3166-2.

**Comment by rposborne** [comment]
@cllns  Excellent, regardless I defer to your knowledge. Thanks for the fantastic PR :trophy:

**Comment by rposborne** [comment]
Merged #212

**Comment by cllns** [comment]
Woo hoo, thanks for being so responsive.
