### ISSUE TITLE
Update the GitHub description

### ISSUE THREAD

**Issue by cllns** [hexorx/countries#213]
Current GitHub description:
***
All sorts of useful information about every country packaged as pretty little country objects. It includes data from ISO 3166 (countries and states/subdivisions ), ISO 4217 (currency), and E.164 (phone numbers). As a bonus it even adds a country_select helper to rails projects.

http://www.countriesgem.com/
***

1. The URL should be removed, since it links to a blank blog.

2. Does this gem add the `country_select` helper? I thought the `country_select` gem does that? That gem requires this one, but this gem doesn't include that functionality.

3. Can we remove the word "pretty" from "pretty little objects"? It feels gendered in a weird way, to me.

**Comment by hexorx** [comment]
Updated.

1. I'll add the link back if I ever get something up on the site. The logo is nice.
2. Good catch. The country_select helper was originally in this gem, but was extracted and the docs weren't updated.
3. Pretty now "convenient".
