### ISSUE TITLE
Including A1 country and others

### ISSUE THREAD

**Issue by Nikamura** [hexorx/countries#234]
We ran into a bug where your library is missing valid country codes such as A1 which references Anonymous Proxy
> http://dev.maxmind.com/geoip/legacy/codes/iso3166/
> http://dev.maxmind.com/geoip/legacy/codes/country_continent/

Would anyone by interested in adding support for this?

**Comment by rposborne** [comment]
So A1 and A2 are not valid country codes outside of Maxmind's database.   Though I can see the real value in it.  I would not accept the AP or EU codes though as we have no support for "Region" country codes.

**Comment by Nikamura** [comment]
Ok, thank you.
