### ISSUE TITLE
BUG: Canada is not in Africa

### ISSUE THREAD

**Issue by tilo** [hexorx/countries#240]
> c = Country.find_country_by_alpha3('CAN")
> c.name
 => "Canada" # so far so good

> c = Country.find_country_by_name('Canada')
> c.name 
  => "Uganda"  # UGANDA???
> c.alpha3
  => "UGA"     # UGANDA???  PENGUINS???
> c.region
 => "Africa"     # outch!

### how can this be tested better?

version 0.11.0

**Comment by tilo** [comment]
sorry, i had a good laugh at this :)

**Comment by douglasr** [comment]
This is because of a change in the "translations.yaml" file -- "Canada" is listed as the "xh" translation for Uganda.

**Comment by rposborne** [comment]
yup, but that file is just a cache of an upstream project i18n_data that has some issues,  we are currently working to figure out the best solution for it.
