### ISSUE TITLE
find_by_name 'Israel' returns Iraq

### ISSUE THREAD

**Issue by SergeyBukhman** [hexorx/countries#241]
The bug is in the translations file line 30085:     oc: Israel

Edit: I fixed it, but you ask not to pull request changes to translations.yaml, so I'll just use my fork until you fix it, I guess

Edit 2: It appears there are many other wrong translations of "Iraq" that point to "Israel" in translations.yaml. So far I've found xh, mt, zu, but only because they use latin letters and it's easy to see. Please check and see what's the origin of this mixup

**Comment by rposborne** [comment]
Interesting these Translations come from upstream @ i18n_data.

**Comment by SergeyBukhman** [comment]
Hey, sorry but it's not fixed.

Try  Country.find_by_name('Israel'). It will return Iraq. Country.find_all_by(:name, 'Israel') returns Israel and Iraq.

**Comment by rposborne** [comment]
Are you sure you are running the latest code... ?  If you are running from the github source make sure you run a ```bundle update countries```.  In the mean time I am adding specs for the two examples and I am unable to repeat the returned values you are reporting.

**Comment by SergeyBukhman** [comment]
Well, my gemfile has countries without a specified version, so I assume it's the latest? I also looked at the code, and indeed it has the change you've made (comment out << translated_names).
