### ISSUE TITLE
BUG: Belgium is not Belize!

### ISSUE THREAD

**Issue by tilo** [hexorx/countries#243]
Complete fail for Belgium as well:

> c = Country.find_country_by_name("Belgium")
> c.name
=> "Belize"
> c.alpha3
=> "BLZ"

this however works:
>  c = Country.find_country_by_alpha3("BEL")
> c.name
=> "Belgium"

Why is this not just a Hash lookup? How can this fail in the first place?
### This gem should have a full coverage test suite to ensure the lookups are correct

**Comment by rposborne** [comment]
It's not a hash lookup as the concept of "name" is not clear cut, each country has many names based upon locale.   

Pull requests are always appreciated.

**Comment by rposborne** [comment]
Actually believe we have test coverage on this, and this does appear to be an upstream issue. 
https://github.com/grosser/i18n_data/blob/master/cache/file_data_provider/countries-XH.txt#L23

In 0.11.0 we swapped out our translation backend to pull from i18n_data to reduce duplication of effort and it seems like we just have a couple of growing pains.

**Comment by tilo** [comment]
thanks for looking at this!

**Comment by rposborne** [comment]
Yea I am going to figure out a somewhat acceptable method fo have a "correction" map for locale + country.  But this is probably best done in the i18n_data will see what we can do for the interim.

**Comment by tilo** [comment]
but how can this be stemming from the L10N data?? I was just looking up the English version of the country name..   In my application I don't even need L10N 

Sorry, I'm super busy at work and can't work on a PR for this. I'd greatly appreciate if would be fixed though.

**Comment by tilo** [comment]
### YOU SHOULD YANK THIS GEM VERSION UNTIL YOU HAVE A FIX!
### PLEASE REVERT TO A STABLE VERSION
