### ISSUE TITLE
Translations for Antilles missing

### ISSUE THREAD

**Issue by 11449** [hexorx/countries#246]
Is there any reason why those translations are missing? 

https://github.com/hexorx/countries/blob/master/lib/cache/translations.yaml#L1079-L1173

**Comment by rposborne** [comment]
Not intentionally no.   We pivoted a bit trying to depend on some other gems for some translations to prevent duplication of effort, but we are having some quality issues with the data.

AN just appears to be fundamentally missing from their source.

**Comment by togiberlin** [comment]
@11449 Please look at this [issue](https://github.com/hexorx/countries/issues/321)
