### ISSUE TITLE
Phone Number Lengths

### ISSUE THREAD

**Issue by nblasgen** [hexorx/countries#247]
I'm trying to do some simple validations for phone numbers based on their length and other things I'd assume I'd be able to do via E164, though I'm now not sure I can.

Italy, being a country I know to be a complicated is my test case.  So my question is, how I can determine acceptable phone number lengths, and to remove or not remove prefixes.

https://github.com/hexorx/countries/blob/master/lib/data/countries/DE.yaml
http://www.howtocallabroad.com/italy/
http://www.itu.int/dms_pub/itu-t/oth/02/02/T020200006B0001PDFE.pdf

1) National_Prefix seems to imply if I'm supposed to drop the leading zero or not.  I'm good with that, since checking something like Germany shows a zero.

2) Country code is clearly defined.  That's good.

3) But what about number length?  Any of the "How to Call" websites mention that Italy is 6 to 10 digits in length.  The other e164 PDF I found implies 3 to 12 digit due to a few government phone numbers (equivalent to 9-1-1 in the USA) being shorter, and a few being longer for some reason.  And then, finally, the data file in this module doesn't seem to have either and instead only lists 9 digits which isn't right in any way possible.  Germany (DE) properly lists multiple number lengths.

So was my test case just a fluke that I found an issue?  Or am I reading the fields wrong?

**Comment by espen** [comment]
Sounds like you want https://github.com/floere/phony

**Comment by nblasgen** [comment]
Well said, and that may be quite useful to me.  But what I actually want is the ability to query the data per country, rather than format a specific number.  With that said though, I do think Phony can be used for what I need.

**Comment by abhishek77in** [comment]
@nblasgen Did find a way to validate international phone number lengths?

**Comment by nblasgen** [comment]
Nope, no luck.  I really only needed it for a limited number of countries, so I just manually created my own configuration file for those specific countries.  If a client of mine needs a new country, I create a new configuration file.

https://github.com/hexorx/countries/blob/master/lib/countries/data/countries/IT.yaml -- this is still wrong (IMHO), so while most countries are likely correct, not all of them are.  Can't depend on them to be valid.

The person who suggested Phony might still be right.  Looking at their code, they seem to process number lengths correctly.  It just didn't meet my needs as it was doing number validation rather than the very narrow use case that I wanted of minimum and maximum number length.  Good luck though on whatever project you're working on.
