### ISSUE TITLE
Bad Belgium Translations

### ISSUE THREAD

**Issue by zedalaye** [hexorx/countries#248]
Are you sure that the belgium translation for "Belgium" is what's in the translations.yaml file ?

```yaml
BE:
  translations:
    ...
    be: "Бельгія"
```

**Comment by zedalaye** [comment]
I filed a bug in the pkg-isocodes bug tracker. What I discovered is that their "be.po" file contains data for "Bielorussian" whose ISO-3166 code is "BY".

**Comment by rposborne** [comment]
@zedalaye fantastic.

**Comment by zedalaye** [comment]
@rposborne according to the isocodes project maintainer response : *PO files represent translation files and are therefore named after **language** codes. "be" is the ISO-669 code for Belarusian. So, the be.po file contains the names of countries in Belarusian, which is perfectly correct*

I think there is a problem with the way the translations file is created because it mixes ISO-.3166 codes for "countries" with ISO-669 codes for "translations".

Or is it on purpose ?

**Comment by rposborne** [comment]
It is on purpose.   The upper most key, is the country, with the inner keys being a "language" code.   This is only to facilitate fast access to this data, vs having to recalculate this at runtime.
