### ISSUE TITLE
sorting by country name

### ISSUE THREAD

**Issue by amolpujari** [hexorx/countries#257]
`Country.order_by_country_name` 

And this should get all the countries sorted by country name.

By default it does sorting by apha2, and when used in dropdown, Germany appears after 'C' and not among 'G's

**Comment by lebrauncom** [comment]
@amolpujari call `.sort` on the returned array. This will order the selected countries by country name instead of country code.
```
Country.all.sort
```

**Comment by pjg** [comment]
I also recommend using https://github.com/grosser/sort_alphabetical

**Comment by guilleart** [comment]
`Country.all.sort` fails in 1.0.0
```
1.9.3-p484 :003 > Country.all.sort
ArgumentError: comparison of ISO3166::Country with ISO3166::Country failed
```

**Comment by rposborne** [comment]
1.1.0 has been released with @guilleart 's compare operation
