### ISSUE TITLE
Priority country

### ISSUE THREAD

**Issue by amolpujari** [hexorx/countries#258]
ability to list countries where specific countries should appear first

**Comment by dugjason** [comment]
Worth noting something similar has been done in SimpleForm; https://github.com/plataformatec/simple_form#priority

**Comment by rposborne** [comment]
Does country_select support priority?   @amolpujari What is the use case for this gem to provide this?

**Comment by dugjason** [comment]
Yeah, it looks like the country_select gem does implement priorities: https://github.com/stefanpenner/country_select#usage

**Comment by rposborne** [comment]
Going to close this as I think it's better to let more "view" libraries handle it.
