### ISSUE TITLE
IOC Codes

### ISSUE THREAD

**Issue by villesundberg** [hexorx/countries#264]
In sports apps, the IOC country codes are often preferable to the ISO 3166-1 codes, as some of them are more readable to English-speakers:

Country | ISO | IOC
---------- | ------ | -------
Algeria | DZA | ALG
Aruba | ABW | ARU
Croatia | HRV | CRO

Would adding the IOC codes be a good idea?

http://en.wikipedia.org/wiki/Comparison_of_IOC,_FIFA,_and_ISO_3166_country_codes

**Comment by rposborne** [comment]
Sure, nil for IOC unrecognized countries? Let me know if you find something the IOC recognizes that we don't

**Comment by rfleury2** [comment]
@villesundberg @rposborne Has anyone tackled this issue yet?  If not, I'd love to give it a shot!

**Comment by villesundberg** [comment]
As far as I can tell, this issue is fixed.

```
2.3.0 :032 > ISO3166::Country.find_country_by_name("Algeria").ioc
 => "ALG" 

```

**Comment by rfleury2** [comment]
@villesundberg Cool.  Just saw the issue and felt it was something I could contribute with.
