### ISSUE TITLE
AU.yaml min/max latitude & min longitude wrong

### ISSUE THREAD

**Issue by pgetto** [hexorx/countries#268]
I think the minimum and maximum latitude values for Australia are incorrect. They should be roughly -9.9 to -43.65 (instead of the current values of -15.5 to -29.472222). My rough estimated values are based on picking some points using Google maps including Tasmania and some of the northern islands. For example: Mabuiag Island QLD, Australia at https://www.google.com/maps/@-9.957615,142.1831004,15z?hl=en and Maatsuyker Island, Tasmania, Australia at https://www.google.com/maps/place/Maatsuyker+Island,+Southwest+National+Park,+Tasmania+7001,+Australia/@-43.6476,146.27755,15z/data=!4m2!3m1!1s0xaa695853cd95fd15:0xf03c94eb451b250?hl=en

Similarly the min longitude value is wrong. Should be roughly 113 (Dirk Hartog Island WA, Australia). Max longitude looks about right for Lord Howe Island, Australia.

**Comment by rposborne** [comment]
A PR would be awesome if you have the time!

**Comment by rposborne** [comment]
@pgetto justed wrote an update script and updated all countries bounding boxes.  Please review here #385
