### ISSUE TITLE
Suggestion :- If some one has one model with the name country in his app and want to use countries gem .

### ISSUE THREAD

**Issue by arvindvyas** [hexorx/countries#276]
I I would like to suggest one think which I  face problem on this , If someone has model name country and want to use'countries' gem without changing anything his application. 
                        I think we should also add in document this scenario that in this situation we can access it by writing ISO3166::Country instead of country.

**Comment by rposborne** [comment]
I tend to agree, I think we will start moving the Country, class to be opt-in vs opt-out or simply deprecate it.

**Comment by rposborne** [comment]
@arvindvyas we have change our default behavior to use ISO3166::Country, you now have to opt-in to get the Country class.
