### ISSUE TITLE
Tag v1.0.0, follow http://semver.org/

### ISSUE THREAD

**Issue by pda** [hexorx/countries#283]
Thanks for your hard work on this library.

Any chance you could tag the current codebase v1.0.0 and (continue to) follow [SemVer](http://semver.org/)? The current v0.x.x isn't really appropriate given the amount of people using it in production; it's implicitly reached v1.x.x status. Setting an arbitrary v1.0.0 base will allow future patches, enhancements and breaking changes to be clearly communicated through the version number.

Cheers!

**Comment by rposborne** [comment]
@pda, we do follow semVer, we just haven't hit what I feel like is a 1.0.0 yet.   There are a couple changes that I think we need to implement, such as eager loading vs load on boot, and some underlying refactoring before this is a 1.0.0 gem.   

The next round of breaking API changes will cause a 1.0.0 bump.

**Comment by pda** [comment]
Thanks for the reply. In my view, a repo with 321 forks and 634 stars (i.e. many production deployments) is implicitly v1.x, and any breaking changes should become v2.x. Put another way, v1 should represent “the first version people are using in the wild”, and then SemVer (post-v1.x) clearly communicates what subsequent versions mean. But, it's your call, I'll drop the subject now :)

**Comment by rposborne** [comment]
Done :)

**Comment by pda** [comment]
Oh nice, thanks very much.
