### ISSUE TITLE
Norway has incorrect un_locode (NL instead of NO)

### ISSUE THREAD

**Issue by ohenrik** [hexorx/countries#291]
Norway should have NO as un_locode, not NL:
https://github.com/hexorx/countries/blob/master/lib/data/countries/NO.yaml#L35

http://www.unece.org/fileadmin/DAM/cefact/locode/no.htm

**Comment by ohenrik** [comment]
Ups, made a mistake when naming the commit. Mixed up NL and NO in the title. Will fix it!

**Comment by rposborne** [comment]
Awesome thanks! 1.1.0 has been released including your fix.

**Comment by ohenrik** [comment]
No problem :cake:
