### ISSUE TITLE
Mongoid 5 throws "uninitialized constant ***::Country"

### ISSUE THREAD

**Issue by govorov** [hexorx/countries#293]
Hi.
After upgrading to mongoid 5, models with Country field defined become broken with this error.

**Comment by rposborne** [comment]
I don't have a good environment to test this in.  Can you provide a sample ?

**Comment by govorov** [comment]
I found, that changing `type: Country` to `type: ISO3166::Country` helps.
I suppose it is all about namespace and it is not a bug at all, but reqiures some chenges in models' code to be compactable with new version of the gem.

**Comment by rposborne** [comment]
Sounds good, i'll close this for now.
