### ISSUE TITLE
Add time zones to country attributes

### ISSUE THREAD

**Issue by esaborit4code** [hexorx/countries#296]
Time zones can be retrieved from [tzinfo](https://github.com/tzinfo/tzinfo)'s [Country class](http://www.rubydoc.info/gems/tzinfo/TZInfo/Country).

**Comment by rposborne** [comment]
I have had a couple other request for this so I think it's pretty reasonable.  How do you think we should do this? just bundle and pass through the TZInfo object?

**Comment by rposborne** [comment]
@esaborit4code Added a PR for passthrough timezone support with TZInfo.   https://github.com/hexorx/countries/pull/311
