### ISSUE TITLE
Is it possible to get language names?

### ISSUE THREAD

**Issue by airblade** [hexorx/countries#302]
I have a Rails app where I would like the user to be able to choose which language they see the site in.  I would like to show them options like English, Deutsch, Français.  Does this gem provide these language names?

**Comment by rposborne** [comment]
@airblade Not directly by one of our dependencies does, [i18n_data](https://github.com/grosser/i18n_data).   Should be what you are looking for

**Comment by airblade** [comment]
Thank you!
