### ISSUE TITLE
Country.find_country_by_name('Canada') returns Uganda

### ISSUE THREAD

**Issue by SergeyBukhman** [hexorx/countries#305]
title, pretty much

**Comment by SergeyBukhman** [comment]
Turns out it also returns Rwanda. It's because of a bad xh translation that says 'Canada' somewhere.

**Comment by rposborne** [comment]
@SergeyBukhman what version are you using... we had some bad translation_names sneak in.  But have since turned this feature of, (where name is so aliased to translated_names)

**Comment by rposborne** [comment]
@SergeyBukhman since we have a regression test for this exact example I am going to close this out. If you are still having issues please let me know.
