### ISSUE TITLE
Don't clobber loadpath with generically named files

### ISSUE THREAD

**Issue by jnicklas** [hexorx/countries#307]
It's good practice in Ruby not to add any generically named files to the root of the loadpath. `countries` adds a file called `global` to the root of the loadpath. To see how this might cause problems it's important to understand that the loadpath is shared between all gems and your application code. This means that if you have any file named `global` at the root of your application's loadpath or any other gem's loadpath anywhere it will conflict with `countries`. It's best practice to create a single file at the root of the loadpath only, named the same as the gem, and to add additional files in a subdirectory.

The structure should look something like this:

```
lib/
├── countries
│   ├── cache/
│   ├── country.rb
│   ├── data/
│   ├── data.rb
│   ├── global.rb
│   ├── iso3166.rb
│   ├── mongoid.rb
│   ├── setup.rb
│   └── version.rb
└── countries.rb
```

**Comment by rposborne** [comment]
@jnicklas Thanks for this. I will get this corrected shortly. Thank you for the well laid out explanation.

**Comment by rposborne** [comment]
@jnicklas I have just release 1.2.1 which has breaking changes to fix this.  Once again thank you, I hope this wasn't at the bottom of a rabbit hole.

**Comment by jnicklas** [comment]
Awesome :) Thanks!
