### ISSUE TITLE
The name of “Saint Vincent And The Grenedines”

### ISSUE THREAD

**Issue by jdudek** [hexorx/countries#310]
There’s a country in the database with name specified as “Saint Vincent And The Gren**e**dines” (its `name` attribute). However, the first item in the attribute `names` says “Saint Vincent and the Gren**a**dines”. According to Wikipedia, the latter is correct: https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines.

**Comment by rposborne** [comment]
Thanks for spotting this, fixed by acfc963f7da022bba1c906444bd4860127fc524c

**Comment by jdudek** [comment]
Awesome, thanks! :)

**Comment by rposborne** [comment]
@jdudek 1.2.2 includes this fix.
