### ISSUE TITLE
Load additional country data (Kosovo)

### ISSUE THREAD

**Issue by svoop** [hexorx/countries#314]
I'm sometimes running into trouble when dealing with bank accounts from Kosovo because it is not present in the data set.

Even though Kosovo is still a disputed area, it's de facto a country. An ISO-Code `XK` and IBAN account number scheme is also in place already. Would it be possible to add Kosovo or – if disputed areas are not wanted in the default dataset – add dispuated areas which have been assigned an ISO-Code in a separate add-on dataset which can be activated/merged by configuration?

**Comment by rposborne** [comment]
Yes, we have some configuration code coming in from the memory refactor branch.  I think adding the ability to load other countries in the data set would be awesome.  Or at least a documented approach to injecting "opinionated" data.

**Comment by basex** [comment]
I think the countries gem could follow a similar path as the money gem to load additional data.

Example:
```ruby
curr = {
  priority: 100,
  iso_code: 'CLF',
  iso_numeric: '990',
  name: 'Unidad de Fomento',
  symbol: 'UF',
  subunit: 'Cent',
  subunit_to_unit: 100,
  separator: ',',
  delimiter: '.',
  symbol_first: true
}

Money::Currency.register(curr)
```

**Comment by rposborne** [comment]
@basex how would you suggest the more complex parts of the country, such as subdivisions and translations?  Just a massive hash?  

I think this is a solid approach regardless.

**Comment by svoop** [comment]
@rposborne I guess, most applications don't use all of the information the gem offers on countries. In fact, a simple country dropdown is probably the most common usecase and what @basex proposed fills this gap perfectly and is easy to handle. In rare, more complex situations, the hash will grow a little more complex as well, shouldn't be a problem.

**Comment by rposborne** [comment]
Tracking support for this in #339

**Comment by barnett** [comment]
@rposborne when using your example:
```ruby
ISO3166::Data.register(
  alpha2: 'XK',
  alpha3: 'XKX',
  name: 'Kosovo, Republic of'
)

ISO3166::Country['US']
=> nil
```
As shown above, it only returns the newly registered country instead of merging it with all the existing countries.  Is there a way to just add it instead of needing to reload all, or am I missing something?

**Comment by barnett** [comment]
@rposborne I was wondering if you have any idea why the above isn't working?  Do I need to register the rest of the data first, then add new instances of data? If so, how do I do that?

Thank you.
