### ISSUE TITLE
Dosn't exist russian translation for "Netherlands Antilles"

### ISSUE THREAD

**Issue by rsmything** [hexorx/countries#321]

**Comment by togiberlin** [comment]
@rposborne Netherlands Antilles was removed from the ISO 3166-1 standard. http://www.iso.org/iso/iso_3166-1_newsletter_vi-8_split_of_the_dutch_antilles_final-en.pdf
Afaik, it ceased to be a country in 2010 was was merged with neighbouring dutch islands.

**Comment by rposborne** [comment]
@togiberlin Awesome thanks for the insight. We will yank the data file.
