### ISSUE TITLE
name for US is "United States", but iso.org lists name as "United States of America" 

### ISSUE THREAD

**Issue by andyt** [hexorx/countries#341]
See https://www.iso.org/obp/ui/#iso:code:3166:US

vs

https://github.com/hexorx/countries/blob/9ad31021a34069c2a7b7beb65c5637d30239dbac/lib/countries/data/countries/US.yaml

"United States" in a country select dropdown list stands out as incorrect.

**Comment by rposborne** [comment]
I am happy to accept a PR.

**Comment by rposborne** [comment]
Please see #384 and provide feedback if you approve.
