### ISSUE TITLE
Feature request : Merge features from 'iso' gem

### ISSUE THREAD

**Issue by n-rodriguez** [hexorx/countries#345]
Hi!

Would it be possible to merge some features from https://github.com/tigrish/iso?
Basically ```iso``` includes :
* reading direction for each country (right to left, left to right)
* plural_rule_names for each country

Here the yml to merge : https://github.com/tigrish/iso/blob/master/data/iso-639-1.yml

Default values :
```
direction: ltr
plural_rule_names: %w(one other)
```

Accepted values :
```
direction: ltr || rtl
plural_rule_names: %w(zero one two few many other)
```

Thanks!

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by rposborne** [comment]
Hey @n-rodriguez, don't want to add this with such an incomplete data set.   We are looking into using the CLDR dataset that has much of this but I haven't had the time to get around too it.   For now if you are focused on the localization aspect you should check out https://github.com/twitter/twitter-cldr-rb

**Comment by n-rodriguez** [comment]
> Hey @n-rodriguez, don't want to add this with such an incomplete data set.

I understand. 

> We are looking into using the CLDR dataset that has much of this but I haven't had the time to get around too it. For now if you are focused on the localization aspect you should check out https://github.com/twitter/twitter-cldr-rb

Thanks for pointing out this link ;)
