### ISSUE TITLE
(Maybe a) Bug in ISO3166::Data.register

### ISSUE THREAD

**Issue by n-rodriguez** [hexorx/countries#362]
I try to register new data for the Kosovo :

in ```config/initializers/countries.rb``` :

```
ISO3166::Data.register(
  alpha2: 'XKX',
  name: 'Kosovo',
  translations: {
    'fr' => 'Kosovo',
    'en' => 'Kosovo'
  }
)
```

But if I do so, Kosovo becomes the only country available in ```country_select```, the other countries are not loaded. To fix this I need to call ```ISO3166::Data.codes``` before ```ISO3166::Data.register``` to load data.

Is this a bug? What am I doing wrong?
Thank you!

**Comment by rposborne** [comment]
@n-rodriguez What version are you running on? We had a bug that is now patched on master where registering a custom country would remove other countries.

**Comment by n-rodriguez** [comment]
2.0.0.0.pre.4

**Comment by rposborne** [comment]
This should be fixed by #360 can you confirm?

**Comment by nlsrchtr** [comment]
I'm running on Rails 3.2.22.5 and Ruby 2.2.3. I'm using the gem through `country_select` where I made a branch with no version dependency on `countries` and added the master branch of `countries` to my `Gemfile`.

Without any call to `ISO3166::Data.register` everything works as expected, but trying to add f.e. Kosovo with:

```ruby
ISO3166::Data.register(
  alpha2: 'XK',
  alpha3: 'XKX',
  name: 'Kosovo, Republic of'
)
```
I see `I18n::InvalidLocale: :de is not a valid locale`. Is this somehow related?

**Comment by nlsrchtr** [comment]
Also if trying to use the example from the README:

```ruby
ISO3166::Data.register(
  alpha2: "LOL",
  name: 'Happy Country',
  translations: {
    'en' => "Happy Country",
    'de' => "glückliches Land"
  }
)
```

the app crashes directly on the console with the following [stacktrace](https://gist.github.com/nlsrchtr/da134bbbe39c862e207f4c5b75e6cf60).

**Comment by rposborne** [comment]
@nlsrchtr I believe this has to do with the specific settings you have inside of the rails app. Namely what locales you are configured as available. I don't think this should be throwing an error on principle, but try only registering translations that your app has enabled. 

```ruby
config.i18n.enforce_available_locales = false
config.i18n.available_locales = [:en, :es, :de]
```

**Comment by nlsrchtr** [comment]
@rposborne thanks for you pointer. It works for me now! Great start into the weekend - thanks again.

**Comment by dennym** [comment]
Sorry about opening this again. Are there any plans on making a gem release with the fix? Im using this gem inside of a gemspec and its impossible to use git there.

**Comment by rposborne** [comment]
@dennym `2.0.0.rc` has been released.

**Comment by dennym** [comment]
Ohh lovely. Didnt expect it to go that fast :)
Did a monkeypatch for the ISO3166::Data#register on my country_select fork. Will switch to the release as soon I get my hands on it again.

thank you
