### ISSUE TITLE
ISO30166::Country.find_by_name returns [c.alpha2, Hash], expected Country or [c.alpha2, Country]

### ISSUE THREAD

**Issue by agraves** [hexorx/countries#363]
Apologies if this is intended behavior. I'm pulling straight off master so I understand things may be in flux.

The `.all` method returns a collection of `ISO3166::Country` objects as I'd expect.

```
irb(main):052:0> ISO3166::Country.all.map(&:class)
=> [ISO3166::Country, ISO3166::Country, ...]
```

But the finder doesn't `.new` the hash.

```
irb(main):051:0> ISO3166::Country.find_by_name('United States').map &:class
=> [String, Hash]
```

It looks like just altering this line: 

https://github.com/hexorx/countries/blob/9ad31021a34069c2a7b7beb65c5637d30239dbac/lib/countries/country/class_methods.rb#L56

From:

`countries = find_by(Regexp.last_match[3], m[1], Regexp.last_match[2])`

to:

`countries = find_by(Regexp.last_match[3], m[1], Regexp.last_match[2], true)`

Would cause it to get wrapped on line 93:

```
    def find_by(attribute, value, obj = nil)
      find_all_by(attribute.downcase, value).map do |country|
        obj.nil? ? country : new(country.last)
      end
    end
```

Anyways thought I'd feel it out before opening a PR. No rush -- I'm wrapping your classes up in my app, but would like to fix this if it's unintended.

Thanks for the useful gem.

**Comment by rposborne** [comment]
I think a change here would have quite a bit of cascading effects, namely it breaks a very large portion of the test suite. Honestly, I am not sure the original motivation behind these return values. @hexorx could you weigh in?

**Comment by rposborne** [comment]
@agraves I think the implementation here is primarily for this data being used for drop down menus.
