### ISSUE TITLE
Error when asking country code for Eslovaquia

### ISSUE THREAD

**Issue by josegrad** [hexorx/countries#364]
It seems that Slovakia's country code cannot be retrieved from its name, in Spanish at least.

```
ISO3166::Country.find_country_by_name('Spain').alpha2
 => "ES" 

ISO3166::Country.find_country_by_name('España').alpha2
 => "ES" 

ISO3166::Country.find_country_by_name('Slovakia').alpha2
 => "SK" 

ISO3166::Country.find_country_by_name('Eslovaquia').alpha2
NoMethodError: undefined method `alpha2' for nil:NilClass

ISO3166::Country[:sk].translation('es')
 => "Eslovaquia" 

```

I have tried with 1.2.5 and with 2.0.0 and both give the same results.

I seem to be tied to 1.2.5 since country_select (https://github.com/stefanpenner/country_select) depends on 1.2 however.

** UPDATE 1 **

The problem seems to be a wrong translation of Slovakia into Spanish.
The correct (or alternative) translation should be 'República Eslovaca'

```
ISO3166::Country.find_country_by_name('República Eslovaca').alpha2
 => "SK" 
```

I can see there's options to correct translations with version 2.0 but I have to use 1.2.5.

** UPDATE 2 **

Same problem with 'Rumanía' - does not work, but 'Rumania' does work.
I'm trying to report it via https://alioth.debian.org/projects/pkg-iso-codes/

**Comment by rposborne** [comment]
@josegrad This sadly is expected behavior, we do not support translation lookup in `find_country_by_name`.  The find by name, is only the english based user and generally only used for quick access,  If you are looking up based upon translations you can you `find_country_by_translated_names`.
