### ISSUE TITLE
Conflict with Exist class Money.

### ISSUE THREAD

**Issue by zephiro** [hexorx/countries#365]
I have model called "Money" 

Error:
superclass mismatch for class Money.

**Comment by SagareGanesh** [comment]
@zephiro can you please provide some extra information related to issue for e.g code snippets so it ll helpful to resolve issue. thanks

**Comment by rposborne** [comment]
@zephiro we have brought in a new library for handling the Currency data, [Money](https://github.com/RubyMoney/money)

**Comment by jeroenvisser101** [comment]
@rposborne that's great, do you mind pushing out a version to rubygems?

**Comment by rposborne** [comment]
@jeroenvisser101 it is.  We are on 2.0.0 pre release.

**Comment by jeroenvisser101** [comment]
Ah, that's cool, thanks! I didn't see that this was included in 2-rc
