### ISSUE TITLE
What's the tips for implementing many-to-many association with AR Model?

### ISSUE THREAD

**Issue by kevin-jj** [hexorx/countries#371]
I assigned a array field in PostgreSQL to build the many-to-many association in our application but I have to load all the countries in the array field to query which country is in the collection.

**Comment by rposborne** [comment]
We aren't storing anything in here as ActiveRecord.  Therefore it would not be a many-to-many, but a single join style table that links to the ISO code. That model would have a method that would load the ISO3166::Country. 

Though since this is not an "issue" per say I will close it regardless.
