### ISSUE TITLE
find_country_by_translated_names(nil) returns Netherlands Antilles

### ISSUE THREAD

**Issue by benldrmn** [hexorx/countries#388]
Hi,
When calling Country.find_country_by_translated_names(nil) or find_country_by_translated_names(''), Netherlands Antilles' country object is returned instead of nil.
This is rather dangerous.

Thanks!

**Comment by rposborne** [comment]
@benldrmn What version of the gem are you using?

**Comment by rposborne** [comment]
I have added a regression test on PR #394 but I have been unable to reproduce on master.
