### ISSUE TITLE
Country.find_country_by_translations always returns nil

### ISSUE THREAD

**Issue by benldrmn** [hexorx/countries#389]
Hi,
Country.find_country_by_translations method always returns nil, even if the translation is a part of the translation hash of a country. Instead, I use the Country.find_country_by_translated_names method which behaves as expected.

This inconsistency is error-prone. If the method does nothing, it's just confusing and better not being defined at all.

Thanks!

**Comment by rposborne** [comment]
@benldrmn I think this method is 100% bug. It appears the old method missing lookup will search by any attribut that is exposed on country.

**Comment by rposborne** [comment]
This should be solved by #393
