### ISSUE TITLE
Add cities to each state in each country

### ISSUE THREAD

**Issue by briosam** [hexorx/countries#402]
This gem is great, will be even better if cities can be added to each states 
[https://en.wikipedia.org/wiki/Lists_of_cities_by_country](url)
As a concrete example China has provinces (states) and each province has a lot of cities [https://en.wikipedia.org/wiki/List_of_cities_in_China](url)

**Comment by rposborne** [comment]
This is a duplicate of #254, please see the discussion there / add to it.
