### ISSUE TITLE
Error in finding country name from country code

### ISSUE THREAD

**Issue by arpitkashyapnestaway** [hexorx/countries#404]
how to find country from country code

Country.find_by_country_code('1')
it is returning only  Virgin Islands, U.S.
where as it should return 
Antigua and Barbuda
Anguilla
American Samoa
Bermuda 

similar problem is for uk

**Comment by rposborne** [comment]
Looks like this pull request is causing the issue.   Most likely will revert and pull the added code out. 
https://github.com/hexorx/countries/pull/392

**Comment by rposborne** [comment]
@arpitkashyapnestaway This is fixed in 2.0.4
