### ISSUE TITLE
Subdivision dataset issues

### ISSUE THREAD

**Issue by Zyphrax** [hexorx/countries#408]
When I compare the subdivisions of Andorra to those of the United States, the data is stored in a different structure:

https://github.com/hexorx/countries/blob/master/lib/countries/data/subdivisions/AD.yaml
https://github.com/hexorx/countries/blob/master/lib/countries/data/subdivisions/US.yaml

This is giving me issues when I use the library.
For example when I grab the first state of Andorra, the name is another struct:

```ruby
irb(main):009:0> Country['AD'].states.first
=> ["02", #<struct ISO3166::Subdivision name=#<struct ISO3166::Subdivision name="Canillo",
 unofficial_names=nil, geo=nil, translations=nil, comments=nil>, unofficial_names=nil,
 geo=nil, translations=nil, comments=nil>]
```

When I grab the first state of the United States, the name is text:

```ruby
irb(main):008:0> Country['US'].states.first
=> ["AA", #<struct ISO3166::Subdivision name="Armed Forces Americas",
 unofficial_names="Armed Forces Americas", geo={"latitude"=>33.8934985, 
 "longitude"=>-117.2732567, "min_latitude"=>33.8403275, "min_longitude"=>-117.2985014,
 "max_latitude"=>33.9460679, "max_longitude"=>-117.2498013},
 translations={"en"=>"Armed Forces Americas"}, comments=nil>]
```

Is this an issue with the dataset or am I doing something wrong?
Thank you for your help.

**Comment by rposborne** [comment]
@Zyphrax Sorry for the slow response, yes you are right this is very wrong.  I just shipped a patch fix that corrects the data set that had these structs embedded in them.  See https://github.com/hexorx/countries/commit/5269e5ffd3055e5a5d6451e5618ba20404ccb333

A new gem has been released with this fix 2.0.5.
