### ISSUE TITLE
Using flags

### ISSUE THREAD

**Issue by MincePie** [hexorx/countries#411]
I'm trying to figure out how to use the countries gem in my Rails 5 app so that I can display a flag emoji in my view.

In my gemfile, I have:

gem 'countries', :require => 'countries/global'
gem 'country_select'

I have a model called **address**. It has an attribute called :**country**

In my address.rb I am trying to copy the gem instructions. The instructions for using the flags say:

Country Code in Emoji

c = Country['MY']
Country.emoji_flag # => "🇺🇸"

The instructions don't make sense to me. What is "c"? Why isn't "c" used in the 2nd line? Why is "Country" a class name when in the examples above, it's an attribute? Do I need to do something to convert my country attribute in my address table into something that the gem can read to determine which flag to present?

None of these questions appear to be answered anywhere. I think this is another instance of things that are assumed that everyone (except for me) seems to intuitively understand. They are roadblocks for me.

In my address model, I have:

  ```
def country_name
    country = self.country
    ISO3166::Country[country]
  end

  def country_emoji
    country.emoji_flag
  end
```
The first method works fine. It displays the right country name.

The second method is my attempt at being able to get a flag. In my address view, I then have:

    `<%=  Address.first.country_emoji %>`
This doesnt work. It produces an error that says:

> undefined method `emoji_flag' for "AU":String

AU is the correct code for the relevant country - so it must be working to figure out which country it should be looking for.

If I try changing the second method (so as to use the first method) to:

```
def country_emoji
    country_name.emoji_flag
  end
```
I get an error that says:

> undefined method `emoji_flag' for #<ISO3166::Country:0x007fe87145d7e0>

Can anyone figure out how to use the countries gem to display a flag?

I saw this post which suggests there is an example app somewhere to show how to apply the instructions in the readme - although that doesnt seem to exist anymore.

**Comment by rposborne** [comment]
I am sorry! Those docs are just wrong.  Two things, you must be on version 2.0 to have the flags. 
Second, the `#emoji_flag` is an instance method on the `Country` class so it should be called as such 
``` ruby
c = Country['US']
c.emoji_flag # => "🇺🇸"
```
In this example, `c` is any instance of the `Country` class.

**Comment by MincePie** [comment]
I am on version 1.2.5, which the gem documentation says is the most recent version. How do I get to version 2?

Once that is answered, how can I used the flag with a variable country attribute?

**Comment by rposborne** [comment]
@MincePie, upgrading your application is very dependent on you.  But if you are using bundler it should be something along the lines of `bundle upgrade countries`.   Though if another one of your gems depends on `countries` you will need to make sure it can be upgraded to the 2.0 release.  A common gem that uses us is `country_select` which will need to be upgraded to their 3.0 release to be able to upgrade. 

 Our most recent release is 2.0.5 as seen on [rubygems](https://rubygems.org/gems/countries).

As for using it, I have provided an example above as well as corrected your documentation, some of the code you presented should work if you were running on the 2.0 version.

**Comment by MincePie** [comment]
Thanks a lot. I've got it going now. Thanks again for the help.
