### ISSUE TITLE
Several non-standard country names

### ISSUE THREAD

**Issue by tom-lord** [hexorx/countries#413]
There are several counties which seem to have incorrectly defined country names, according to the ISO standard. I have not yet found an easy way to compile a full list, but here are a few:

* Code: VN. [Gem's name](https://github.com/hexorx/countries/blob/master/lib/countries/data/countries/VN.yaml#L10): "Vietnam". [ISO 3166 name](https://www.iso.org/obp/ui/#iso:code:3166:VN): "Viet Nam".
* Code: TW. [Gem's name](https://github.com/hexorx/countries/blob/master/lib/countries/data/countries/TW.yaml#L15): "Taiwan, Republic Of China". [ISO 3166 name](https://www.iso.org/obp/ui/#iso:code:3166:TW): "Taiwan, Province of China"
* Code: KP. [Gem's name](https://github.com/hexorx/countries/blob/master/lib/countries/data/countries/KP.yaml#L10): "Korea, Democratic People's Republic Of", [ISO 3166 name](https://www.iso.org/obp/ui/#iso:code:3166:KP): "Korea (the Democratic People's Republic of)"

I presume that this gem's data was seeded using some script, but I don't know how/where the data was sourced from. Are these discrepancies justified by your source, or is some of the data in fact subtly incorrect?

**Comment by rposborne** [comment]
@tom-lord our data set is far far far from new, or programmatic. The name function primarily serves a purpose of approachability so a developer knows which files are being worked with, but as we understand the primary use case for this gem are the translations of those country names.   

That being said, those other two suggestions are hot topics, and any change to the official ISO spec normal is met with resistance.  We hope someday to add modes to recognize various countries that are "disputed"

**Comment by tom-lord** [comment]
Hi @rposborne, thanks for the quick response.

I was hoping to use this gem as part of an interface to a legacy system, to create a mapping between country names (provided by the legacy application) to the associated alpha2 country code. For example:

    ISO3166::Country.find_country_by_name("United Kingdom").alpha2 # => "GB"

However, due to the above issue, this approach fails in a few odd scenarios, such as:

    ISO3166::Country.find_country_by_name("Taiwan, Province Of China") # => nil

It would therefore be valuable for me to have to have the country names updated to the current ISO 3166 standard.

I would be happy to write a simple script to perform this update, if you are OK with such a merge? I suspect Taiwan is the only "controversial" country name that would be significantly affected by this, but at the end of the day this gem _is_ simply supposed to be representing the current ISO standard.

**Comment by rposborne** [comment]
@tom-lord I would accept a pull request that makes these changes, as this name is primarily not used in what is presented to users (country_select uses the translations)

**Comment by tom-lord** [comment]
I just made this code change with a quick+dirty script, based on this Wikipedia table: https://en.wikipedia.org/wiki/ISO_3166-1

I've also done some spot checks on the ISO website (as linked to in my original post), and everything seems consistent.
