### ISSUE TITLE
Singapore & Norway province codes

### ISSUE THREAD

**Issue by jaketay** [hexorx/countries#422]
Both the Singaporean and Norwegian province/subdivision codes include the country code such as [SG-02](https://github.com/hexorx/countries/blob/master/lib/countries/data/subdivisions/SG.yaml#L14) and [NO-03](https://github.com/hexorx/countries/blob/master/lib/countries/data/subdivisions/NO.yaml#L26). 

All the other countries seem to split the province code and country code. Is this intended for the SG and NO province codes?

**Comment by rposborne** [comment]
@jaketay these are indeed the correct country codes based upon the ISO spec.  The others (most) are incorrect and need to be updated.
