### ISSUE TITLE
Mongoid Document without Country raises error

### ISSUE THREAD

**Issue by exocode** [hexorx/countries#434]
When I try to save a country within a mongoid Document, and recall it, I got the following:

```
class Place
  field :country, type: Country // also not working with something like: `default: -> { false }`
  field :name, type: String
end

Place.create(name: "Demo Place")

Place.where(:country.exists => true).count
Place.where(:country.ne => nil).count

```
Both raises:
`
ISO3166::Country::BadMongoidTypeError: Given value is neither a valid country object nor a valid alpha2 code
`

Hopefully someone helps me out

Thank you

**Comment by rposborne** [comment]
@exocode Apologies, would you mind making a simple test repo to reproduce (you have done a great job already).

**Comment by exocode** [comment]
thank you for your response... I simply updated the gem, and it's working now!
