### ISSUE TITLE
Some countries are missing subdivisions

### ISSUE THREAD

**Issue by jawnsy** [hexorx/countries#437]
Some countries have subdivisions that are not reported by the countries gem, because the corresponding data file is missing.

* [GL (Greenland)](https://en.wikipedia.org/wiki/ISO_3166-2:GL)
* [LC (Santa Lucia)](https://en.wikipedia.org/wiki/ISO_3166-2:LC)
* [MC (Monaco)](https://en.wikipedia.org/wiki/ISO_3166-2:MC)
* [PS (State of Palestine)](https://en.wikipedia.org/wiki/ISO_3166-2:PS)
* [SS (South Sudan)](https://en.wikipedia.org/wiki/ISO_3166-2:SS)
* [TJ (Tajikistan)](https://en.wikipedia.org/wiki/ISO_3166-2:TJ)
* [WF (Wallis and Futuna)](https://en.wikipedia.org/wiki/ISO_3166-2:TJ)

I found these by looking at the [list of subdivisions defined by the CLDR dataset](http://www.unicode.org/cldr/charts/30/supplemental/territory_subdivisions.html) and noting the ones where no corresponding `data/subdivisions/xx.yaml` file exists.

**Comment by rposborne** [comment]
@jawnsy would you look over #473

Their data should be fleshed out further but it's in much better shape.
