### ISSUE TITLE
Incorrect Language spoken for Nepal

### ISSUE THREAD

**Issue by gkunwar** [hexorx/countries#440]
Here is the list of Top languages spoken in Nepal.

- Nepali 
- Maithili
- Bhojpuri
- Tharu
- Tamang
- Nepal Bhasa
- Bajjika
- Magar
- Dotyali
- Urdu
- Awadhi
- Limbu
- Gurung

**Comment by rposborne** [comment]
@gkunwar Would you mind compiling the ISO codes for these languages?

**Comment by gkunwar** [comment]
ISO 639-2 Code of following languages:
Nepali: nep
Maithili: mai
Bhojpuri: bho
Nepal Bhasa: new
Urdu: urdf

**Comment by gkunwar** [comment]
@rposborne I'm planning to fix this issue myself. Let me know if there anything that I need to follow rule while creating pull request.
