### ISSUE TITLE
Search country by country code

### ISSUE THREAD

**Issue by ziaulrehmandevsinc** [hexorx/countries#441]
I am trying to get country by country code. When I do:

`ISO3166::Country.find_all_by('country_code', "1")`

I get array of 25, while i am expecting it to return only united states?

Problem I am trying to solve is that **I have country code** which is country_code in this gem, and I want to get that country's  **International Call Prefix**. Which is international_prefix in this gem.

I know this might be expected behaviour. If any one can guide me about this, that will be great. Thank-you.

**Comment by rposborne** [comment]
I think you are hitting the North American Numbering plan that share the 1 digit prefix.   https://en.wikipedia.org/wiki/North_American_Numbering_Plan

This is regretfully the "correct" response.

**Comment by ziaulrehmandevsinc** [comment]
Thank-you for the response @rposborne

I expected that this is correct behaviour. But if you(or anyone) can guide me in solving the problem that will be great?

Should i save country name instead of country code in my DB, so i can get use find_country_by_name and than extract country code and international code easily from that. Though, this approach will cause me to extract country code every-time i need it.
