### ISSUE TITLE
All the translations of the countries in Portuguese from Brazil (br) are in english

### ISSUE THREAD

**Issue by basex** [hexorx/countries#448]
The problem was created on this commit: https://github.com/hexorx/countries/commit/d5a87a5b9e180eb8f0e85c95ccf607eb7a2034fd

The translations were converted to English.

Some translations like Venezuela (VE) show now as Romania in the locale 'br' :/

**Comment by basex** [comment]
Yes I was refering to pt-BR, in some systems is mapped as 'br' that's why I was confused. At some point the translations were in pt-BR but then they changed to another language.

**Comment by rposborne** [comment]
@basex No worries, glad we got it solved. Thank you for pointing it out, it's people like you who keep this data up to date. So I should be thanking you!
