### ISSUE TITLE
CHANGELOG falling behind

### ISSUE THREAD

**Issue by phantomwhale** [hexorx/countries#466]
I note that there hasn't been a change log update for the last few minor versions - is that due to nothing of note, or has this been perhaps overlooked by accident?

**Comment by rposborne** [comment]
@phantomwhale I have been neglecting the changelog if only the underlying data set is changing.   

This an open source project with a single maintainer.  I find it much more important to accept PR's and ensure that the data set is staying up to date, versus delaying content changes till when I have free time to write out a changelog.  (I am not a huge fan of "read the commits" style changelogs.

**Comment by rposborne** [comment]
@phantomwhale I updated the changelog. https://github.com/hexorx/countries/blob/master/CHANGELOG.md
