### ISSUE TITLE
Missing VAT rates

### ISSUE THREAD

**Issue by jgrau** [hexorx/countries#469]
This is more a question than an issue:

Some countries are missing VAT rate information. Is there a reason for that? Would you merge a PR that set vat rate for eg. Norway?

**Comment by rposborne** [comment]
Yup any correction to the data set will be happily merged.   

Look forward to your PR @jgrau!

**Comment by jgrau** [comment]
Cool. I tried to find a way to automate the fetching of vat rates but even finding a proper dataset seems like a challenge. The best I found was http://www.vatlive.com/vat-rates/international-vat-and-gst-rates/ and tried to get in touch with them to see if they exposed their data in json or csv but I never got a reply.
