### ISSUE TITLE
Improve matching of find_country_by_name

### ISSUE THREAD

**Issue by jonathantribouharet** [hexorx/countries#470]
Hi,
I had a problem matching a country because the `'` character was `’`.
The matching doesn't work in this case.

Example:
```
ISO3166::Country.find_country_by_name "CÔTE D’IVOIRE" # return nil
ISO3166::Country.find_country_by_name "CÔTE D'IVOIRE" # work fine
```

**Comment by rposborne** [comment]
@jonathantribouharet I think the handling of smart quotes might be outside of the scope of this project.  It might be best to handle this input sterilization before calling into countries. 

Maybe `"CÔTE D’IVOIRE".gsub("’", "'")`
