### ISSUE TITLE
all_subdivisions_names_with_codes

### ISSUE THREAD

**Issue by md-hamed** [hexorx/countries#479]
Hello,
First, thank you for this beneficial gem.
In our project, we needed to have a select list for countries that populates another list of subdivisions. So basically when you choose a country, the subdivision list gets updated accordingly. 
We needed to add a method called `all_subdivisions_names_with_codes(locale)` on a `Country`, just similar to `all_names_with_codes(locale)`. It helps in implementing the described kind of behavior. I find this a popular use case, thus, I'm wondering if it's desirable to have this feature built in the library. 
Should I PR?

**Comment by rposborne** [comment]
Sounds reasonable, Yea a PR would be great!

**Comment by md-hamed** [comment]
@rposborne 
* Please note that I haven't used `html_safe` here for the name of the subdivision as done in `all_names_with_codes` as I see no reason for using it in the first place. Please confirm that this is true.
* There are some subdivisions with no name. Is there a plan to resolve this by adding the missing names to the subdivision data or should I fallback to the English translation?

**Comment by BillyParadise** [comment]
awesome. very useful. was trying to figure out how to accomplish this myself.
