### ISSUE TITLE
Overriding/Extending Country class with custom methods

### ISSUE THREAD

**Issue by exocode** [hexorx/countries#506]
Hi there, I wanna be able to extend the ``Country`` class by my custom methods.
But it seems Ruby/Rails is taking the Country class from the gem and not from my models.

Creating a ``country.rb`` in my ``app/models`` directory with the following content:

```ruby
require "countries/version"

require 'iso3166'
require 'countries/mongoid' if defined?(Mongoid)

class Country < ISO3166::Country

  @country_index = []

  def to_s
    self.name
  end
  
  def subdivision_index
       # my content here
      puts "TEST"
  end

```

Calling 

```
c = Country.search("AT")
c.subdivision_index

```
raises an error 

```
c.subdivision_index
NoMethodError: undefined method `subdivision_index' for #<Country:0x007fe910800bc8>
Did you mean?  subdivisions
```

**How can I achieve that?**

The reason is, that I wanna save all countries in a db and make them searchable via ElasticSearch.
Thank you!

**Comment by rposborne** [comment]
Hm. 

1. What version are you running on? 
2. Are you requiring the global adapter in your gemfile?

**Comment by exocode** [comment]
Hm it seems "countries" gem had some progress in the last years :-)
I am using a custom branch, with some subdivisions added by myself. In order to switch to the actual hexorx version all of these subdivisions should be merged into the "original" one (yours). Is that possible to make a pull request? (all my added stuff is conform to the one of hexorx)

**Comment by rposborne** [comment]
@exocode We always accept PR's for new content, as long as it's valid, and not political charged.

**Comment by rposborne** [comment]
@exocode going to close this.  Please reopen if you still need help on this.
