### ISSUE TITLE
Kosovo independent from Serbia

### ISSUE THREAD

**Issue by MorneL** [hexorx/countries#511]
Kosovo is a country that has been rendered independent from Serbia, but in the data here it says it's a subdivision of Serbia. We're using this gem in a countries select dropdown but we can't get Kosovo to be one of the countries. 

Any way around this?

**Comment by neohunter** [comment]
I'm not able to find Kosovo. Where do you find it?

**Comment by ksz2k** [comment]
I had to workarount it with:

```ruby
ISO3166::Data.register(
  alpha2: "XK",
  alpha3: "XKX",
  name: 'Kosovo',
  currency: 'EUR',
  translations: {
    'en' => "Kosovo"
  }
)
```

**Comment by tomrossi7** [comment]
Should I submit a PR to add this?

**Comment by pmor** [comment]
We follow ISO data, and Kosovo is not yet present as an independent country in the ISO data set. The workaround mentioned above is what I've also used on several projects.

This issue has already come up a few times and will continue to be rejected until ISO releases a new data set.

**Comment by Gerst20051** [comment]
If you are using an older version of this library you should be able to update the data cache like this:

```ruby
ISO3166::Country::Data.delete('AN')
ISO3166::Country::Data['XK'] = {
  'alpha2' => 'XK',
  'alpha3' => 'XKX',
  'name' => 'Kosovo',
  'currency' => 'EUR',
  'translations' => {
    'en' => 'Kosovo'
  }
}
ISO3166::Country::Data = ISO3166::Country::Data.sort.to_h
ISO3166::Country::Names = ISO3166::Country::Data.map { |k,v| [v['name'], k] }.sort_by { |d| d[0] }
ISO3166::Country::NameIndex = Hash[*ISO3166::Country::Names.flatten]
```
