### ISSUE TITLE
Push new release to Rubygems.org?

### ISSUE THREAD

**Issue by SeriouslyAwesome** [hexorx/countries#545]
Hey guys. First of all, thanks for this gem–it's super helpful.

I wanted to nudge you guys towards pushing a new version to Rubygems.org. I just spent the better part of an hour banging my head on the keyboard trying to figure out why `ISO3166.configuration.enable_currency_extension!` (as documented in the README) was returning a `NoMethodError` and finally figured out that it was because that method [was added in July](https://github.com/hexorx/countries/commit/b5f8edc1852f64742e25bdee9f75fe51368b0136) but there hasn't been a new release pushed to Rubygems.org since February.

Obviously I can pull the gem from `master` here, but hopefully a version bump will prevent others from sharing my experience. Thanks again!

**Comment by rposborne** [comment]
Sure thing.

**Comment by rposborne** [comment]
Cut version 2.2

**Comment by SeriouslyAwesome** [comment]
Thanks!
