### ISSUE TITLE
currency feature can be turned off?

### ISSUE THREAD

**Issue by torumori** [hexorx/countries#551]
In the README, it implies currency feature could be turned off, but not implemented yet, right?
It seems to be turned on by default, and the config option `enable_currency_extension` doesn't seem to exist.
We have a large application which has the top level class named `Money`, and I've realized I can't use this awesome gem without a change.
If the above assumption is correct, can someone tell me if any plan to implement it?
If there is a config option to disable it, can someone clarify it as well?
Thank you!

**Comment by rposborne** [comment]
@torumori what version are you using?

**Comment by torumori** [comment]
@rposborne I'm currently testing with the latest release version, v2.1.4.

**Comment by rposborne** [comment]
@torumori I am going to cut a new release in the next couple minutes that will include this feature.

**Comment by rposborne** [comment]
I cut 2.2.0 which should include the new `enable_currency_extension` feature

**Comment by torumori** [comment]
Thank you very much. I will try 2.2.0.

**Comment by torumori** [comment]
@rposborne we still use Rails 4.2, and i18n gem is 0.9.5 which prevents bundler from installing countries v2.2.0 which depends on i18n v1.0.1 or higher.
Though we plan to upgrade to Rails 5.x sometime soon, I think I need to backport only the `enable_currency_extension` portion into v2.1.4 so we can develop a feature meanwhile.
I'm not familiar with how you organize the branches for countries gem, but do you have any branch holding the v2.1.4 release?

```
Bundler could not find compatible versions for gem "i18n":
  In snapshot (Gemfile.lock):
    i18n (= 0.9.5)

  In Gemfile:
    activeresource (= 4.0.0) was resolved to 4.0.0, which depends on
      activesupport (~> 4.0) was resolved to 4.2.10, which depends on
        i18n (~> 0.7)

    countries (= 2.2.0) was resolved to 2.2.0, which depends on
      i18n (> 1.0.1)

```

**Comment by rposborne** [comment]
@torumori It may be possible to relax the i18n restriction, I would try that first via a fork and see if that solves your issues.

**Comment by rposborne** [comment]
@torumori looks like the hard dependency to i18n was accidentally added and is not needed. 

https://github.com/hexorx/countries/pull/558

**Comment by torumori** [comment]
@rposborne Thank you so much!
