### ISSUE TITLE
Release '3.0.0' missing some commits

### ISSUE THREAD

**Issue by MOOn2k** [hexorx/countries#603]
What we see on your github repositories '3.0.0' branch doesn't match to what we get after 'bundle installing' your gem.

To repeat this issue:
0. remove all 'countries' gem installations
1. create a gemfile with this line and make a bundle install
```
gem 'countries', '3.0.0'
```
2. go to the folder where it's installed and check for this changes for example
https://github.com/hexorx/countries/commit/8158e77261f4b0bb636e9800ababcb5555aa2150
3. you wont find any

You may even add this and there's still will be the same difference with the master branch
```
gem 'countries', git: 'https://github.com/hexorx/countries.git', branch: 'master'
```

**Comment by rposborne** [comment]
Yea, I really borked some git during the 3.0.0 release.   https://rubygems.org/gems/countries/versions/3.0.1 has been cut.  Closing this.
