### ISSUE TITLE
Please cut a release

### ISSUE THREAD

**Issue by inopinatus** [hexorx/countries#610]
Keen to have i18n_data 0.10.0 in particular.

**Comment by pmor** [comment]
@hexorx @rposborne There's quite a few outstanding PRs with data corrections and updates. 

I'm particularly concerned with the upcoming Brexit date in two days. I'm setting up a fork for that in the meantime, but a new release would be most welcome.

Do you need an extra hand?

**Comment by rposborne** [comment]
@pmor Always up for more folks to support.  As this project just has constant churn.

**Comment by rposborne** [comment]
@inopinatus https://rubygems.org/gems/countries/versions/3.0.1 has been cut. Closing.
