### ISSUE TITLE
The name for Vietnam is incorrect 

### ISSUE THREAD

**Issue by SylvieC** [hexorx/countries#660]
The name for the country of Vietnam is incorrect. It should be  one word (**Vietnam** instead of **Viet Nam**) 

The error in in  countries/lib/countries/data/countries/VN.yaml
name should be changed to **Vietnam**
<img width="1369" alt="Screen Shot 2021-02-05 at 4 20 38 PM" src="https://user-images.githubusercontent.com/5790222/107090413-2c5abc80-67ce-11eb-9e89-b14d56afe670.png">

I am not sure if I am allowed to make a pull request

**Comment by pmor** [comment]
I just checked ISO (https://www.iso.org/obp/ui/#iso:code:3166:VN) and officially, it is written Viet Nam. I know its probably not the spelling most people use, but this gem follows ISO naming.

Perhaps the translations have the more common spelling? I know that is the case for the UK, for example.

Regarding pull requests, as far as I can tell, anyone can submit new PRs.

**Comment by SylvieC** [comment]
Thanks.
